---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://api.tender.wtf/hc/stats?username={{ username }}&bearer={{ bearerToken }}
polling_headers: ''
id: 63345
custom_fields:
- keyname: bearerToken
  field_type: string
  name: Bearer Token
  description: Copy value from https://hardcover.app/account/api
  placeholder: Bearer xxx
- keyname: featuredArea
  field_type: select
  options:
  - Goals # value will be 'goals'
  - Recently Read # value will be 'recently_read'
  - Currently Reading # value will be 'currently_reading'
  - Shuffle Want To Read # value will be 'shuffle_want_to_read'
  default: goals
  name: Featured Area
  description: Select what appears in the lower half in a full view.
name: Hardcover Stats
refresh_interval: 360
